### ISSUE TITLE
Combine forces with Enigma VM?

### ISSUE THREAD

**Issue by wanton7** [kvakvs/ErlangRT#14]
Maybe this project should combine forces with Enigma VM? https://github.com/archseer/enigma

**Comment by wanton7** [comment]
I wrote this before watching ErlangRT Code BEAM video. It seems that you have been in contact with Enigma VM developer already.

**Comment by kvakvs** [comment]
I don't like some choices and shortcuts he made, i'm writing things the way they should be, which is slower. His goal is to run Elixir ASAP, so I've noticed he uses temporary solutions.

Not sure if showing running Elixir or Erlang shell sooner is worth anything, it is not like there are investors waiting to see a prototype. So my values are different too.
