### ISSUE TITLE
Make make_fun and call_fun work

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/ErlangRT#3]
- [x] verify that make_fun works correctly
- [x] verify that call_fun works

**Comment by tekknolagi** [comment]
Is this related to the `panic!` in call_closure.rs? If so, anything I can do to help?

**Comment by kvakvs** [comment]
It has to be implemented, the code is missing.
For that I need to focus and do something, like write some code.

It should store current IP in CP, set arg registers and jump to the code. Similar to apply and call and call_ext
