### ISSUE TITLE
OTP 21 and OTP 22 BEAM compatibility

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/ErlangRT#5]
Something changed in BEAM format in OTP 21+
Figure out and fix the loader

**Comment by fcevado** [comment]
isn't bc of this one:
https://github.com/erlang/otp/pull/1367

**Comment by kvakvs** [comment]
Something also changed in opcodes, the loader is confused.
I will read through this, thanks a lot!

**Comment by kvakvs** [comment]
Switched to 22 and for simplicity there is no looking back, for now.
